version: '3'

services:

  app:
    build:
      context: ../
    container_name: go-container
#    restart: on-failure
    environment:
      - PROJECT_NAME=user-service
      - HTTP_PORT=8080
      - HTTP_TIMEOUT=60 #in seconds
      - WSS_PORT=8081
      - WSS_TIMEOUT=60 #in seconds
      - STATUS_PORT=8082
      - STATUS_TIMEOUT=60 #in seconds
#    depends_on:
#      - postgresdb
    networks:
      - go-application


#  redis:
#    image: redis:7
#    container_name: redis-go-template
#    ports:
#      - 6379:6379
#    restart: always
#
#
#  postgresdb:
#    image: postgres:latest
#    container_name: postgres_container
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#      - DATABASE_HOST=${DB_HOST}
#    ports:
#      - '1234:5432'
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#    networks:
#      - go-application

#volumes:
#  pg_data:
#  pg_data_test:

networks:
  go-application:
    driver: bridge